# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f26ac5198219764aed2affd38e5e8e5081284d2cb88ba3e6954990651fcb6065bb1a9cb35d92911defab3f4d841efd3ceb99c663775653a4a1a761447206467

test:
  secret_key_base: 957eaef58d93b6ed20cee2e151bc70a54b5bef3306c5e4c524da5199b21f948308aef6eea1d4be953bcfa186c63e2187b7325e6e70f5d1e0c9770fbfe452ae00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
 '81dfdfd30360333f67699fff154f6571edbfa2f293e05d53653306fd2e1008c61b4a1a917bcd1347f2e7e52f29dfde8359a083d4f8fc51f30edc5161707770a3'
